### ISSUE TITLE
new first_ancestor descriptor causes crash on empty desks

### ISSUE THREAD

**Issue by ortango** [baskerville/bspwm#1089]
Hi, I'm seeing a little issue with the new descriptor. Bspwm is seg faulting if I query first_ancestor on an empty desktop. eg `bspc query -N @next.!occupied: -n first_ancestor`

**Comment by ortango** [comment]
```
#0  0x000055e941d8fba1 in find_first_ancestor (ref=ref@entry=0x7ffe01658840, dst=dst@entry=0x7ffe01658a00, sel=sel@entry=0x7ffe01658880) at src/tree.c:1020
        loc = {monitor = 0x55e942b201a0, desktop = 0x55e942b20510, node = 0x0}
#1  0x000055e941da2f3b in node_from_desc (desc=<optimized out>, ref=0x7ffe01658840, ref@entry=0x7ffe016589e0, dst=dst@entry=0x7ffe01658a00) at src/query.c:555
        ref_copy = {monitor = 0x55e942b201a0, desktop = 0x55e942b20510, node = 0x0}
        desc_copy = 0x55e942b19560 "@^2:/"
        hash = <optimized out>
        path = <optimized out>
        colon = 0x55e942b19563 ":/"
        sel = {automatic = OPTION_NONE, focused = OPTION_NONE, active = OPTION_NONE, local = OPTION_NONE, leaf = OPTION_NONE, window = OPTION_NONE, tiled = OPTION_NONE, pseudo_tiled = OPTION_NONE, floating = OPTION_NONE, fullscreen = OPTION_NONE, hidden = OPTION_NONE, sticky = OPTION_NONE, private = OPTION_NONE, locked = OPTION_NONE, marked = OPTION_NONE, urgent = OPTION_NONE, same_class = OPTION_NONE, descendant_of = OPTION_NONE, ancestor_of = OPTION_NONE, below = OPTION_NONE, normal = OPTION_NONE, above = OPTION_NONE, horizontal = OPTION_NONE, vertical = OPTION_NONE}
        dir = 479
        cyc = (unknown: 556431602)
        hdi = (HISTORY_NEWER | unknown: 32594)
#2  0x000055e941d9d809 in cmd_query (args=0x55e942b20a58, args@entry=0x55e942b20a48, num=1, num@entry=3, rsp=rsp@entry=0x55e942b19380) at src/messages.c:1055
        ret = <optimized out>
        ref = {monitor = 0x55e942b201a0, desktop = 0x55e942b202e0, node = 0x55e942b20660}
        trg = {monitor = 0x0, desktop = 0x0, node = 0x0}
        monitor_sel = 0x0
        desktop_sel = 0x0
        node_sel = 0x0
        dom = DOMAIN_NODE
        print_ids = true
        d = 1 '\001'
#3  0x000055e941d9e082 in process_message (args=0x55e942b20a48, args@entry=0x55e942b20a40, num=3, num@entry=4, rsp=rsp@entry=0x55e942b19380) at src/messages.c:95
No locals.
#4  0x000055e941d9e1bc in handle_message (msg=0x7ffe01658e40 "query", msg_len=33, rsp=0x55e942b19380) at src/messages.c:82
        cap = 8
        num = 4
        args = 0x55e942b20a40
        args_orig = 0x55e942b20a40
#5  0x000055e941d8b24f in main (argc=1, argv=0x7ffe0165af78) at src/bspwm.c:198
        rsp = <optimized out>
        pr = <optimized out>
        descriptors = {__fds_bits = {16, 0 <repeats 15 times>}}
        socket_path = "/tmp/bspwm_0_0-socket", '\000' <repeats 234 times>
        state_path = '\000' <repeats 255 times>
        sock_fd = 4
        cli_fd = 5
        dpy_fd = 3
        max_fd = <optimized out>
        n = <optimized out>
        sock_address = {sun_family = 1, sun_path = "/tmp/bspwm_0_0-socket", '\000' <repeats 86 times>}
        msg = "query\000-N\000-n\000@^2:/#first_ancestor\000\000loating\000desktop=STEAM\000\000loating", '\000' <repeats 8127 times>
        event = <optimized out>
        end = 0x0
        opt = <optimized out>
```
