### ISSUE TITLE
Segfault in update_motion_recorder

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#728]
When running `bspc desktop -m prev/next`, bspwm (HEAD) segfaults.

```
>>> bt
#0  update_motion_recorder () at src/window.c:739
#1  0x000055555556039a in focus_node (m=m@entry=0x555555785760, d=d@entry=0x555555785a50, n=<optimized out>) at src/tree.c:587
#2  0x000055555555b618 in transfer_desktop (ms=0x5555557856d0, md=0x555555785760, d=0x555555785a50) at src/desktop.c:173
#3  0x00005555555699aa in cmd_desktop (args=0x555555784fa0, num=1, rsp=rsp@entry=0x55555578d650) at src/messages.c:648
#4  0x000055555556b5c0 in process_message (args=<optimized out>, num=<optimized out>, rsp=0x55555578d650) at src/messages.c:92
#5  0x000055555556b7e1 in handle_message (msg=0x7fffffffb6e0 "desktop", msg_len=<optimized out>, rsp=0x55555578d650) at src/messages.c:81
#6  0x0000555555557bc5 in main (argc=<optimized out>, argv=<optimized out>) at src/bspwm.c:170
>>> info locals
pt = {
  x = 2271, 
  y = 805
}
win = 81788931
m = 0x5555557856d0
d = 0x0
n = 0x0
```

Very rarely, it seems to work the first time around.

**Comment by baskerville** [comment]
Thanks!
