### ISSUE TITLE
bspwm freezes with 100% CPU usage

### ISSUE THREAD

**Issue by imiric** [baskerville/bspwm#977]
Hi, thanks for this lovely WM. I've been using it for years without a hitch, until a few weeks ago when I started using [conky-bspwm-desktops](https://github.com/drasill/conky-bspwm-desktops), which is a small Lua script for Conky to show, well, bspwm desktops and it's quite nice.

Before pointing the finger at Conky or the Lua script, I wanted to first run this by the bspwm community since it is bspwm that's exhibiting the lockup and high CPU usage.

The issue is the following: very frequently (multiple times a day now), bspwm will stop responding to any bspc commands, it will peg a CPU core to 100%, and will need to be SIGTERM killed. Since it's the main X11 process, as you can imagine it brings down X with it along with all of my work. :(

I haven't been able to pinpoint the exact sequence of commands that puts it in this state. Sometimes it happens with many windows on many desktops, and other times with only a few.

I did, however, compile it with debug flags, and have a core dump as well as a sysdig trace of both bspwm and conky when the issue happens.

Here's the stack trace:

```
#0  find_closest_node (ref=0x7fffe8672880, dst=0x7fffe86729e0, dir=CYCLE_NEXT, sel=0x7fffe86728c0) at src/tree.c:1621
        m = 0x564451802400
        d = 0x5644518096d0
        n = 0x56445180a110
#1  0x00005644510922d9 in node_from_desc (desc=0x56445180b710 "next", ref=0x7fffe8672880, dst=0x7fffe86729e0) at src/query.c:547
        ref_copy = {monitor = 0x564451802400, desktop = 0x5644518093c0, node = 0x0}
        desc_copy = 0x56445180b710 "next"
        hash = 0x0
        path = 0x0
        colon = 0x0
        sel = {automatic = OPTION_NONE, focused = OPTION_NONE, active = OPTION_NONE, local = OPTION_TRUE, leaf = OPTION_NONE, window = OPTION_NONE, tiled = OPTION_NONE,
          pseudo_tiled = OPTION_NONE, floating = OPTION_NONE, fullscreen = OPTION_NONE, hidden = OPTION_NONE, sticky = OPTION_NONE, private = OPTION_NONE, locked = OPTION_NONE,
          marked = OPTION_NONE, urgent = OPTION_NONE, same_class = OPTION_NONE, descendant_of = OPTION_NONE, ancestor_of = OPTION_NONE, below = OPTION_NONE, normal = OPTION_NONE,
          above = OPTION_NONE}
        dir = DIR_NORTH
        cyc = CYCLE_NEXT
        hdi = HISTORY_OLDER
#2  0x0000564451086916 in cmd_node (args=0x56445180c420, num=1, rsp=0x564451801340) at src/messages.c:148
        ret = 32767
        dst = {monitor = 0x564451802400, desktop = 0x5644518093c0, node = 0x0}
        ref = {monitor = 0x564451802400, desktop = 0x5644518093c0, node = 0x0}
        trg = {monitor = 0x564451802400, desktop = 0x5644518093c0, node = 0x0}
        changed = false
#3  0x000056445108650d in process_message (args=0x56445180c418, num=2, rsp=0x564451801340) at src/messages.c:89
No locals.
#4  0x00005644510864b4 in handle_message (msg=0x7fffe8672e60 "node", msg_len=19, rsp=0x564451801340) at src/messages.c:82
        cap = 8
        num = 3
        args = 0x56445180c410
        args_orig = 0x56445180c410
#5  0x0000564451073491 in main (argc=1, argv=0x7fffe8674f58) at src/bspwm.c:196
        rsp = 0x564451801340
        pr = 0x0
        descriptors = {__fds_bits = {16, 0 <repeats 15 times>}}
        socket_path = "/tmp/bspwm_0_0-socket", '\000' <repeats 234 times>
        state_path = '\000' <repeats 255 times>
        sock_fd = 4
        cli_fd = 5
        dpy_fd = 3
        max_fd = 4
        n = 19
        sock_address = {sun_family = 1, sun_path = "/tmp/bspwm_0_0-socket", '\000' <repeats 86 times>}
        msg = "node\000-f\000next.local\000\000\000hidden\000-f\000\000\000ating\000focus=on\000\000ngle=1918x500+0+28", '\000' <repeats 8124 times>
        event = 0x0
        end = 0x0
        opt = -1
```

I took a look at `src/tree.c:1621`, but my C knowledge is rusty at best and I wouldn't know where to start debugging this.

Here's my [bspwmrc](https://github.com/baskerville/bspwm/files/3258280/bspwmrc.gz) (gzipped because of GitHub), the [core dump](https://github.com/baskerville/bspwm/files/3258282/bspwm-freeze.core.gz) and the [sysdig trace](https://github.com/baskerville/bspwm/files/3258285/bspwm-conky-20190605-freeze.log.gz). Let me know if you need more information.

Any help with this is highly appreciated.

Thanks for your hard work!

**Comment by imiric** [comment]
Thanks for the quick fix! I'm testing it now, but I think you got it. I am using hidden windows, so it seems right.

Cheers!
